### ISSUE TITLE
Empty Accessible Volume

### ISSUE THREAD

**Issue by mathicm** [RNA-FRETools/fretraj#1]
Hi, 
I would like to try FRETraj as an alternate to FPS which has issue running on Mac. I followed your tutorial but I get empty accessible volume error, I can't also select donor or acceptor please see the screenshots. Do you have parameters file to load set of donor acceptor pairs? 
<img width="1058" alt="Screen Shot 2021-02-20 at 9 16 15 AM" src="https://user-images.githubusercontent.com/31673579/108600522-3dbecf80-735d-11eb-9ca7-fcfd8d589c9d.png">
<img width="972" alt="Screen Shot 2021-02-20 at 9 16 04 AM" src="https://user-images.githubusercontent.com/31673579/108600544-5af39e00-735d-11eb-8bbe-dc1ae905f7f1.png">

I would appreciate your help.
Thank you
Mathi

**Comment by fdsteffen** [comment]
Hi Mathi,
Thanks for your report. Try running the ACV calculation without LabelLib (i.e. deactivate the checkbox "use LabelLib") to see if the issue persists.
Kind regards, Fabio

**Comment by mathicm** [comment]
Hi Fabio,

It is working now without the use of LabelLib. Thank you so much.

Mathi
